---
title: "Institutional Research Analyst Interview"
author: "Naomi Liftman"
date: "`r Sys.Date()`"
output: pdf_document
---
# Load Packages
```{r message = FALSE, warning = FALSE, error = FALSE}
#loading the necessary packages
library(tidyverse)
library(ggplot2)
library(rio)
library(gt)
library(ggthemes)
library(gridExtra)
```

# Graph and Data for Bac vs other Schools
```{r}
#import the green and the totals
justgreen <- import("/Users/naomiliftman/Desktop/Coding_Samples/Green River College/Cred detail Table_green.xlsx")
total <- import("/Users/naomiliftman/Desktop/Coding_Samples/Green River College/Cred detail Table_total.xlsx")

#pivot longer for the green 
greenpivot <- justgreen %>%
  pivot_longer(!`Summary Level`, names_to = "year", values_to = "count") %>% 
  rename(level = 1) %>% 
  filter(level!= "Apprenticeship")

#pivot total
totalpivot <- total %>%
  pivot_longer(!`Summary Level`, names_to = "year", values_to = "count") %>% 
  rename(level = 1)

only_bac <- greenpivot %>% 
  filter(level == "Applied Baccalaureate")
```

```{r warning = FALSE}
#graph greenriver alone! 
ggplot(data = greenpivot, aes(x = year, y = count, color = level, 
                              group = level, color = level)) + 
  geom_point() +
  geom_line(linewidth = 1.2) + 
  labs(title = "Green River College Awards Between 2012 and 2023", y = 'Number of Awards', x = 'Year', plot.title = element_text(hjust = 0.5)) +
  scale_color_manual(values = c("#d62976", "#800080", "#0c457d", "#FC913A"), name = "") + 
  theme_economist()
```

```{r}
#graph greenriver with just bac 
ggplot(data = only_bac, aes(x = year, y = count, color = level, 
                              group = level, color = level)) + 
  geom_point() +
  geom_line(linewidth = 1.2) + 
  labs(title = "Green River College Baccalaureate Between 2012 and 2023", y = 'Number of Awards', x = 'Year') +
  scale_color_manual(values = c("#d62976"), name = "") + 
  theme_economist()
```


```{r}
#making it comparable to green river 
total_compare <- totalpivot %>% 
  filter(level != "Apprenticeship") %>% 
  filter(level != "Non-Credit")

#graph totals
ggplot(data = total_compare, aes(x = year, y = count, color = level, 
                              group = level, color = level)) + 
  geom_point() +
  geom_line(linewidth = 1.2) + 
  labs(title = "Comparable College Awards Between 2012 and 2023", y = 'Number of Awards', x = 'Year') +
  scale_color_manual(values = c("#d62976", "#800080", "#0c457d", "#FC913A"), name = "")+ 
  theme_economist()
```

# 2014 vs 2023 Graphs and Data

```{r}
#import the 2014 information and use options(scipen=999) to get rid of scientific notation
compare_2014 <- import("cred by college table_2014.xlsx") 
names(compare_2014)<-make.names(names(compare_2014),unique = TRUE)

# create a nicer version to then be able to pivot
attempts_14 <- compare_2014 %>%
  slice(which(row_number() %% 3 == 1)) %>% 
  rename(college = 1)  %>% 
  select(college, Applied.Baccalaureate:Basic.Skills)

#remove the grand total before pivoting
attempts_14 <- attempts_14[-c(34), ]

attempts_14 <- attempts_14 %>% 
  rename(Baccalaureate = 2,
         "Basic Skills" = 6)

#pivoting now 
pivot_2014 <- attempts_14 %>%
  pivot_longer(!`college`, names_to = "type_of_degree", values_to = "count") 

pivot_2014_attempts <- pivot_2014

pivot_2014_attempts[pivot_2014 == "Baccalaureate"] <- "BAC"
pivot_2014_attempts[pivot_2014 == "Associate"] <- "ASO"
pivot_2014_attempts[pivot_2014 == "Apprenticeship"] <- "APR"
pivot_2014_attempts[pivot_2014 == "Certificate"] <- "CRT"
pivot_2014_attempts[pivot_2014 == "Basic Skills"] <- "BAS"
```

```{r}
#graph 2014
p14 <- ggplot(data = pivot_2014_attempts, aes(x = type_of_degree, y = count, color= ifelse(college == "Green River", "Green River", "Other Colleges"))) + 
  geom_point(show.legend = FALSE) +
  labs(title = "Total Awards 2014", y = 'Percent of all Awards', x = 'Type of Awards', color = "College") +
  scale_color_manual(values = c("#317873", "#ff93ac")) + 
  theme_minimal()
```

```{r}
#import the 2014 information and use options(scipen=999) to get rid of scientific notation
compare_2023 <- import("cred by college table_2023.xlsx") 
names(compare_2023)<-make.names(names(compare_2023),unique = TRUE)

# create a nicer version to then be able to pivot
attempts_23 <- compare_2023 %>%
  slice(which(row_number() %% 3 == 1)) %>% 
  rename(college = 1)  %>% 
  select(college, Applied.Baccalaureate:Basic.Skills)

#remove the grand total before pivoting
attempts_23 <- attempts_23[-c(34), ]

attempts_23 <- attempts_23 %>% 
  rename(Baccalaureate = 2,
         "Basic Skills" = 6)

#pivoting now 
pivot_2023 <- attempts_23 %>%
  pivot_longer(!`college`, names_to = "type_of_degree", values_to = "count") 

pivot_2023_attempts <- pivot_2023

pivot_2023_attempts[pivot_2023 == "Baccalaureate"] <- "BAC"
pivot_2023_attempts[pivot_2023 == "Associate"] <- "ASO"
pivot_2023_attempts[pivot_2023 == "Apprenticeship"] <- "APR"
pivot_2023_attempts[pivot_2023 == "Certificate"] <- "CRT"
pivot_2023_attempts[pivot_2023 == "Basic Skills"] <- "BAS"
```

```{r}
#graph 2014
p23 <- ggplot(data = pivot_2023_attempts, aes(x = type_of_degree, y = count, color= ifelse(college == "Green River", "Green River", "Other Colleges"))) + 
  geom_point(show.legend =  FALSE) +
  labs(title = "Total Awards 2023", y = 'Percent of all Awards', x = 'Type of Awards', color = "College") +
  scale_color_manual(values = c("#317873", "#ff93ac")) + 
  theme_minimal() +
  ylim(0.00, 0.25)
```

```{r warning = FALSE}
grid.arrange(p14, p23, ncol = 2)
```


# Green vs others over time
# Creating my own Green Data
```{r}
#import just the green data 
green <- import("cs_bar_green.xlsx")
names(green)<-make.names(names(green),unique = TRUE)

#rename!
green <- green %>% 
  rename(total =4)

#filling the years and the summary levels 
green_years <- green %>% 
  fill(Academic.Year) %>% 
  fill(Summary.Level)  %>% 
  filter(total == "Total") %>% 
  mutate(College.Name = "Green River") %>% 
  filter(Summary.Level != "Non-Credit")

#converting all the data hopefully into one column but includes NAs
green_years <- unite(green_years, col = "count", c("X2013", "X2014", "X2015", "X2016", "X2017", "X2018", "X2019", "X2020", "X2021", "X2022", "X2023"), sep = "")

#remove all the NAs from our number columns and then convert to numeric 
green_years$count <- gsub("NA", "", green_years$count)
green_years$count <- as.numeric(green_years$count)
```

# Clark Time
```{r}
#import just the green data 
clark <- import("cs_bar_clark.xlsx")
names(clark)<-make.names(names(clark),unique = TRUE)

#rename!
clark <- clark %>% 
  rename(total =4)

#filling the years and the summary levels 
clark_years <- clark %>% 
  fill(Academic.Year) %>% 
  fill(Summary.Level)  %>% 
  filter(total == "Total") %>% 
  mutate(College.Name = "Clark") %>% 
  filter(Summary.Level != "Non-Credit")

#converting all the data hopefully into one column but includes NAs
clark_years <- unite(clark_years, col = "count", c("X2013", "X2014", "X2015", "X2016", "X2017", "X2018", "X2019", "X2020", "X2021", "X2022", "X2023"), sep = "")

#remove all the NAs from our number columns and then convert to numeric 
clark_years$count <- gsub("NA", "", clark_years$count) 
clark_years$count <- as.numeric(clark_years$count)
```

# Bates 
```{r}
#import just the bates data 
bates <- import("cs_bar_bates.xlsx")
names(bates)<-make.names(names(bates),unique = TRUE)

#rename!
bates <- bates %>% 
  rename(total =4)

#filling the years and the summary levels 
bates_years <- bates %>% 
  fill(Academic.Year) %>% 
  fill(Summary.Level)  %>% 
  filter(total == "Total") %>% 
  mutate(College.Name = "Bates") %>% 
  filter(Summary.Level != "Non-Credit")

#converting all the data hopefully into one column but includes NAs
bates_years <- unite(bates_years, col = "count", c("X2013", "X2014", "X2015", "X2016", "X2017", "X2018", "X2019", "X2020", "X2021", "X2022", "X2023"), sep = "")

#remove all the NAs from our number columns and then convert to numeric 
bates_years$count <- gsub("NA", "", bates_years$count) 
bates_years$count <- as.numeric(bates_years$count)
```

# Everett 
```{r}
#import just the everett data 
everett <- import("cs_bar_everett.xlsx")
names(everett)<-make.names(names(everett),unique = TRUE)

#rename!
everett <- everett %>% 
  rename(total =4)

#filling the years and the summary levels 
everett_years <- everett %>% 
  fill(Academic.Year) %>% 
  fill(Summary.Level)  %>% 
  filter(total == "Total") %>% 
  mutate(College.Name = "Everett") %>% 
  filter(Summary.Level != "Non-Credit")

#converting all the data hopefully into one column but includes NAs
everett_years <- unite(everett_years, col = "count", c("X2013", "X2014", "X2015", "X2016", "X2017", "X2018", "X2019", "X2020", "X2021", "X2022", "X2023"), sep = "")

#remove all the NAs from our number columns and then convert to numeric 
everett_years$count <- gsub("NA", "", everett_years$count) 
everett_years$count <- as.numeric(everett_years$count)
```


# Graphs!
```{r warning = FALSE}
#graph of clark
ggplot(clark_years, aes(x = Academic.Year, y = count, group = Summary.Level, color = Summary.Level)) + 
  geom_point(show.legend = FALSE) +
  geom_line(linewidth = .8, show.legend = FALSE) +
  scale_color_manual(values = c( "#8a2be2", "#ff1493", "#000080", "#00eeee", "#66cd00"))  +
  labs(title = "Clark", x = "Year", y = "Count", color = "Award Type") +
  ylim(0, 2200) +
  theme_bw() 

#graph of green
ggplot(green_years, aes(x = Academic.Year, y = count, group = Summary.Level, color = Summary.Level)) + 
  geom_point(show.legend = FALSE) +
  geom_line(linewidth = .8, show.legend = FALSE) +
  scale_color_manual(values = c( "#8a2be2", "#ff1493", "#000080", "#00eeee", "#66cd00"))  +
  labs(title = "Green River", x = "Year", y = "Count", color = "Award Type") +
  ylim(0,2200)+
  theme_bw()

#graph of bates
ggplot(bates_years, aes(x = Academic.Year, y = count, group = Summary.Level, color = Summary.Level)) + 
  geom_point(show.legend = FALSE) +
  geom_line(linewidth = .8, show.legend = FALSE) +
  scale_color_manual(values = c( "#8a2be2", "#ff1493", "#000080", "#00eeee", "#66cd00"))  +
  labs(title = "Bates", x = "Year", y = "Count", color = "Award Type") +
  ylim(0,2200)+
  theme_bw()

#graph of everett
ggplot(everett_years, aes(x = Academic.Year, y = count, group = Summary.Level, color = Summary.Level)) + 
  geom_point(show.legend = FALSE) +
  geom_line(linewidth = .8, show.legend = FALSE) +
  scale_color_manual(values = c( "#8a2be2", "#ff1493", "#000080", "#00eeee", "#66cd00"))  +
  labs(title = "Everett", x = "Year", y = "Count", color = "Award Type") +
  ylim(0,2200)+
  theme_bw()
```

# Combining
```{r}
#combining clark and green river to make a prettier version! lmao
grid.arrange(p_clark, p_green, p_bates, p_everett, ncol = 4)
```






